name: Update README with latest blog posts

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 00:00에 실행 (UTC 기준)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install feedparser
      - name: Run update script
        run: python updateReadMeAuto.py
      - name: Commit and push if changed
        run: |
          git config --local user.email "gusdudco6@naver.com"
          git config --local user.name "CheHyeonYeong"
          git add README.md
          git commit -m "Update README with latest blog posts" || echo "No changes to commit"
          git push
